### ISSUE TITLE
Add post type 'page' to reports

### ISSUE THREAD

**Issue by bamadesigner** [bcole808/wp-social-metrics-tracker#17]
I added the plugin to one of our sites where I'd like to see social metrics for pages and noticed they're missing from the reports. Looks like you make sure 'page' and 'attachment' are removed. I'm fine with 'attachment' but I'd like to see the stats for my pages.

I did a little digging and discovered the plugin is actually keeping metrics for pages. It stops the metrics for 'attachment' and anything that isn't set to 'publish' so pages go through, you just have them removed from the dashboard query.

I can understand why some people wouldn't want to see pages, especially if its a blog or news site or something. What do you think about adding "Report Post Types", with probably a better name :), to settings?

**Comment by bcole808** [comment]
I agree! There should be a configuration to allow people to select the post types to track and display (this should encompass posts, pages, and custom post types - but not attachments). I think the options panel should ideally show a list of all the currently registered custom post types and allow each to be checked and un-checked. Then I think it would be helpful to have a filter displayed on the reporting page to show or hide the different post types.

**Comment by bamadesigner** [comment]
Agreed.
