### ISSUE TITLE
PHP notices if no options have been setup

### ISSUE THREAD

**Issue by bamadesigner** [bcole808/wp-social-metrics-tracker#28]
Just a quick FYI: If you install the plugin and go to the main "Social Metrics Tracker" page before you setup your options, you get a notice for each post type so, for example, you'd get:
- Undefined index: smt_options_post_types_post
- Undefined index: smt_options_post_types_page

and then your custom post types:
- Undefined index: smt_options_post_types_people
- Undefined index: smt_options_post_types_events

**Comment by bcole808** [comment]
Thanks, good catch!
