### ISSUE TITLE
DIsplaying multiple admin_notices

### ISSUE THREAD

**Issue by bamadesigner** [bcole808/wp-social-metrics-tracker#48]
Hi!

Just wanted to let you know about a small bug I came across.

In your lib/wp-settings-framework.php, you have it set to show settings_errors() in your admin_notices() function. The problem comes on pages that are already set to automatically show settings error, i.e. settings pages.

I was working on a plugin of mine and wondering why "Settings saved" was being spit out twice. WordPress automatically prints out settings errors on settings pages so I did some backtracing and the duplicate settings errors are coming from your plugin.

Thanks!

**Comment by bcole808** [comment]
Awesome, I had been trying to figure out why I have duplicate "Settings saved" messages for a long time. Fixing it now. Thanks!

**Comment by bamadesigner** [comment]
Great! Thanks!
