### ISSUE TITLE
Undefined index: smt_options_debug_mode

### ISSUE THREAD

**Issue by bamadesigner** [bcole808/wp-social-metrics-tracker#52]
Just wanted to let you know after I updated to 1.4.0, I now get the following notice:

Undefined index: smt_options_debug_mode
wp-content/plugins/social-metrics-tracker/social-metrics-tracker.php:148

**Comment by bcole808** [comment]
Thanks as always! =)

**Comment by bamadesigner** [comment]
You're welcome, as always. Thanks for the great plugin! :)
