### ISSUE TITLE
Tracking of attachment pages should also be possible 

### ISSUE THREAD

**Issue by thomaslhotta** [bcole808/wp-social-metrics-tracker#67]
Hi,

On line 178 of `MetricsUpdater.class.php` you remove attachments from the array of trackable post types. On my page I get quite a lot of likes on attachment pages for images, so it would be really nice to allow tracking of attachments.

**Comment by bcole808** [comment]
Hi, this should be quick and easy to add this. I will see if I have time within the next few weeks to work on it and get it into the next release. 

_(If anyone else has the time to make a pull request, the desired functionality should be that attachments are disabled by default, but can be enabled via the list of custom post types in the settings area for the plugin. Currently they are removed from the list of options, as noted above)_

**Comment by thomaslhotta** [comment]
I created a pull request #68 with the changes. Also added some minor improvements.

**Comment by bcole808** [comment]
Thanks! (Github isn't sending me notification emails for some reason so I just discovered this now)

I'll take a look at it within a day or two and merge if it all looks good.
